version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      PRE_START_PATH: ./prestart.sh
      WORKER_CLASS: uvicorn.workers.UvicornWorker
      db_url: postgresql://postgres:1234@postgres:5432/todo
    networks:
      - backend
    ports:
      - "80:80"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24

volumes:
  postgres-data: