"""added_foreignkey_user

Revision ID: 5a0210e42620
Revises: 415b113abe65
Create Date: 2021-01-14 16:47:37.744129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a0210e42620'
down_revision = '415b113abe65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_crossed_out', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cards_pkey')
    )
    # ### end Alembic commands ###
